-- NOT NULL Constraint
ALTER TABLE students
MODIFY COLUMN name VARCHAR(50) NOT NULL;

-- UNIQUE Constraint
ALTER TABLE students
ADD CONSTRAINT unique_email UNIQUE(email);

-- DEFAULT VALUE
ALTER TABLE students
ADD COLUMN country VARCHAR(20)
DEFAULT 'India';

-- CHECK CONSTRAINT
ALTER TABLE students
ADD CONSTRAINT chk_age CHECK (age > 20);

SELECT * FROM students;